/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary-container": "#dc2626",
        "tertiary-container": "#906b38",
        background: "#191211",
        "inverse-surface": "#efdfde",
        "on-primary-fixed-variant": "#93000b",
        "on-primary-container": "#fff6f5",
        surface: "#191211",
        secondary: "#e7bdb7",
        "inverse-primary": "#bf0715",
        "on-primary-fixed": "#410002",
        "surface-container-highest": "#3c3332",
        "on-secondary-fixed-variant": "#5d3f3b",
        primary: "#ffb4ab",
        "on-secondary": "#442a26",
        tertiary: "#edbe84",
        "on-background": "#efdfde",
        "on-tertiary": "#462b00",
        "secondary-fixed": "#ffdad5",
        "surface-variant": "#3c3332",
        "outline-variant": "#5c403c",
        "on-primary": "#690005",
        "primary-fixed-dim": "#ffb4ab",
        "on-error": "#690005",
        outline: "#ac8884",
        "error-container": "#93000a",
        "surface-container": "#261e1d",
        "surface-container-low": "#221a19",
        "on-surface-variant": "#e6bdb8",
        "on-tertiary-fixed-variant": "#604011",
        "on-secondary-fixed": "#2c1512",
        "on-tertiary-container": "#fff6f0",
        "on-secondary-container": "#d4aca6",
        "surface-container-high": "#312827",
        "primary-fixed": "#ffdad6",
        "tertiary-fixed": "#ffddb5",
        "on-tertiary-fixed": "#2a1800",
        "surface-dim": "#191211",
        "on-surface": "#efdfde",
        "surface-container-lowest": "#130c0c",
        "surface-tint": "#ffb4ab",
        error: "#ffb4ab",
        "secondary-fixed-dim": "#e7bdb7",
        "tertiary-fixed-dim": "#edbe84",
        "inverse-on-surface": "#372e2e",
        "on-error-container": "#ffdad6",
        "secondary-container": "#5d3f3b",
        "surface-bright": "#403736",
        "error-dim": "#c44b5f",
        "secondary-dim": "#d8afa9",
        "primary-dim": "#e9a9a1",
        "tertiary-dim": "#f0c187"
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px"
      },
      spacing: {
        xs: "4px",
        md: "16px",
        xl: "48px",
        unit: "4px",
        lg: "24px",
        gutter: "24px",
        sm: "8px",
        "container-max": "1200px"
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "headline-lg": ["Inter"],
        "body-md": ["Inter"],
        "display-xl": ["Inter"],
        "headline-md": ["Inter"],
        "label-sm": ["Inter"],
        headline: ["Inter"],
        display: ["Inter"],
        body: ["Inter"],
        label: ["Inter"]
      },
      fontSize: {
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "700" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
        "display-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "800" }],
        "headline-md": ["24px", { lineHeight: "1.3", letterSpacing: "-0.01em", fontWeight: "700" }],
        "label-sm": ["14px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "600" }]
      }
    }
  },
  plugins: [],
};
